# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Z2ffsHQfxs/bEf1s/CM1O8R99O3Y15TDEQvSbosT2Fi7sWHviKnfWXrAnPZK9Rgji2yVfNPmNmUQSZ7ZzKRb+0mfSE+C6/AEFm+qOMjDaIWmvcb15Xhbg3KXdXiIaGgWOz7zJQIL6RL2LTzBCk2nFYtjQe7TziAnTov5Ij1jG9TMxbr5+y+0VLWX2M9cAXao9j+DJTLPTCeM9AHoAMOtGoo6y1Trb9JiwaIX7Se4u6727eHu7korasdHBlKTRN9SO8GMnm6asgm2yBcd4HDDYyM/DMhLdPqdspFqQ8yihofg9NdyT/cFd/EyAxX+bK+D74dkkZb2ZUWCg0yDRHshDJP+OZOCJKpez0gMM91PF9f8kYc57MJEbCxSIQzbAEM6x/gRezsmWK7+J2EXzL+afLrFeiL98hhDT3XyQWJxaIdXJgpH8efJE+B8BKw1nLYCCxJs6hZLuHK0ZilWIqM0kJdTdioTssYeGPY/Yn8GvbYt26CMN10tsmKxmwY64flygClXylsf5B7dPeMvQC1ye+uuAW1XaU/fZJZiYPseU+emqA+U939k1T34Vnsoj8TJwqMOXhhquGQTu9jL83bjp3aS5NihwN1zFI8XQsNczCidhAeSeQfEMqegDO5TwU0UqLJGvrAbLt+ZvADj5bSO/ILm1CoYAdGVjOYV+YIcuvo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
