travis:
  secure:
    BINSTAR_TOKEN: qbTOocr1ZgSM8s/JP0QOtReh7U5WpwaNwcfy+A9rchKmiU3kBWMJ/mQu+2bVFolcFdIdwtuDTnNxi98Bm8eO4lL886lWrTSNe+8PNwD2C0/ReFHIpLriHIUP/QAPp3zUVeXoFyh/XHwTVK9ZWM20aK8MUppToXeGCZp3sI8exXRCN7IQ5q/xAtLWpHjsDUnWVDVU40TFpjhhBBS2w87vtiuzfkAlc9b3WoBfjhp0gAolmLMssz9aO5NYxalBqROkw3ZAD2toZqsQFRqMqTXqKv6Of7xmbhDa91+vISJxm/zo5ffo5zOxK8ms8An3+i3BdwNds+GbTWX10GEporc37gnREidIWnHlKtAgs1W8FHrNMQ0Lu4w5VUGEorr08QUjuAPBDU2r9P0p2KZj9U/CDT8eCAZ9z5o3Fvw4lAAWXl28c6QzBZZ4t/A+q2+fVbcXQ5mx64L600LeBDOmIJ6athknre/sj2xpuDchqHmQpjyjwC/gtR//zBZEXf/7vNJB1t9kyKEUfAIrTMULtz/TwF+a1DADfuatgvJ8JSyBMe2QTARewNaicEZ3Aj307dx2h+tMl4IHLVCiEWJuasfKKFLSGLqDNt2AmJ80pVdLRq3u1Rw72JiqGUxbL63oi3n5MF9a1YEPRtGIQOZ4c7xv4lknoS2hKCxj2ntmCemb1c8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
