travis:
  secure:
    BINSTAR_TOKEN: Z2ffsHQfxs/bEf1s/CM1O8R99O3Y15TDEQvSbosT2Fi7sWHviKnfWXrAnPZK9Rgji2yVfNPmNmUQSZ7ZzKRb+0mfSE+C6/AEFm+qOMjDaIWmvcb15Xhbg3KXdXiIaGgWOz7zJQIL6RL2LTzBCk2nFYtjQe7TziAnTov5Ij1jG9TMxbr5+y+0VLWX2M9cAXao9j+DJTLPTCeM9AHoAMOtGoo6y1Trb9JiwaIX7Se4u6727eHu7korasdHBlKTRN9SO8GMnm6asgm2yBcd4HDDYyM/DMhLdPqdspFqQ8yihofg9NdyT/cFd/EyAxX+bK+D74dkkZb2ZUWCg0yDRHshDJP+OZOCJKpez0gMM91PF9f8kYc57MJEbCxSIQzbAEM6x/gRezsmWK7+J2EXzL+afLrFeiL98hhDT3XyQWJxaIdXJgpH8efJE+B8BKw1nLYCCxJs6hZLuHK0ZilWIqM0kJdTdioTssYeGPY/Yn8GvbYt26CMN10tsmKxmwY64flygClXylsf5B7dPeMvQC1ye+uuAW1XaU/fZJZiYPseU+emqA+U939k1T34Vnsoj8TJwqMOXhhquGQTu9jL83bjp3aS5NihwN1zFI8XQsNczCidhAeSeQfEMqegDO5TwU0UqLJGvrAbLt+ZvADj5bSO/ILm1CoYAdGVjOYV+YIcuvo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
