appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: BthkSQGdWytN4rBU0FUqM1qh9DwdKVYLMdaZbMdQV2d+eUJIwH9edlMdalNeEEU8zAPvHDvYGO6fpfCh2RMLM0uI9aD0okgmG8JMDfrQi1jW4YrklhSGiRYvwPZMyai2ZLtwnQSJXS9z/MyDjX0VE+gs4t/1wy+AkEDdP4vSKl+eXxq5ASQNBvNjxhENCtW9GD3w4zsKp4h0/xxsZ2Uh1bo2qonR41hm60+zbnzhlzhLsVVopxIHCuxLQkZvrztst98RiroEuI5urjN2+dcc6gg4gJA2272zomsfbsrW7O9yLEfSYOwrj27OAh2m9jEGwxaMovwTGcZlof/okpHN4QTOXceMGs5ljVf/gKWipHo8Ej+IUYaMRz6hN/QSq+fmR3L8N9D6kQkxutbDsOPRW9cgXM1WN7SGP/B67lgQZdAcMvMlJKJCiNU2wr4Yq8MvNmPemz14LxFWpC83M2/d3IBKWwKpq8rmRH9oTH+2aTfKv/N2+/x4+3YaGtsxaVaa6IxsvPvzDGX9GGwghjP2Si3tLpMlPXLK6pAvxIOZ3Gr5KN4fV0QdLCeofWCF8VFlvruQrQeRb+WZq3cH6gHayaRXRoq2UjOptUBoX1HR8o9L/IjgU2AXVz+xAZxMjound2C/NKB4a7iepaaHX5zgPQVB3t4+CmwDLzuo6wndy2w=}
